### ISSUE TITLE
"Sort applist A-Z" menu item launches the wrong tool

### ISSUE THREAD

**Issue by bmn001** [OnionUI/Onion#1511] opened 2024-03-19 00:12 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

Selecting "Sort applist A-Z" will pop up a screen briefly that says:

`Tool: build_short_rom_game_list
Applying tool...`

That's not the correct tool.

Selecting "Generate game list for short name roms" from this menu generates that same message.

### Steps to Reproduce

- Launch Apps/Tweaks/Tools.
- Select "Sort applist A-Z"

### Provide any additional context or information that may help us investigate your issue

No additional info.

**Comment by tGecko** [comment] 2024-03-19 05:42
Fixed in #1448 

the issue is only visual, it still launches the correct tool.

**Closed by tGecko** 2024-03-19 05:42 UTC
