### ISSUE TITLE
Manage file corruption and boot loops

### ISSUE THREAD

**Issue by schmurtzm** [OnionUI/Onion#775] opened 2023-04-12 21:10 UTC
Due to the FAT32 and the SD card support itself, there are often users who meet some data corruption during the Onion install install (at this moment the SD card is very solicited in read and write) which triggers boot loop.
I don't know if we can imagine something against the boot loop.
May be in case of bootloop there is a way to intercept it and triggers a fsck on the SD card and then display "reinstall Onion" .

Due to hotswap I have often SD card corruption that I fix with scandisk on windows, may be fsck could make the same correction on Fat32 volumes ?

We could keep the last Onion setup files somewhere and restore it in case of corruption / boot loop after a checkdisk.

(By the way putting some "sync" commands each time we write something seems to be a good idea to avoid corruption )

Nice to have but low priority on this task.

**Comment by Aemiii91** [comment] 2023-07-04 11:39
Closing as done. Also, since fw 0505 `tee` in `main` has been removed (this was the cause of some corruptions).

Related PRs:
- #958 
- #941 
- #932 
- #911

**Closed by Aemiii91** 2023-07-04 11:39 UTC
Labels: enhancement
