### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by Hai1979** [OnionUI/Onion#1061] opened 2023-07-25 23:31 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

onion v4.2.0-rc

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

When I log into Retro Achievents and put my password and user name and save the configuration and log in to my game and when I switch games the game switch is kinda slow to switch different games on.

### Steps to Reproduce

Please provide detailed steps that will help us replicate and investigate your issue

### Provide any additional context or information that may help us investigate your issue

1. log in to Retro Achiventments and password
2. turn on the Achiventments
3. pick a game
4. use the game switcher 
5. it slow to catch the next game on RetroAchievents

**Comment by Aemiii91** [comment] 2023-07-25 23:37
Duplicate of https://github.com/OnionUI/Onion/issues/848

**Closed by Aemiii91** 2023-07-25 23:37 UTC
