### ISSUE TITLE
[MainUI] - Onion 4.2 Beta 4 Not Finding All Roms

### ISSUE THREAD

**Issue by GrouchyM** [OnionUI/Onion#852] opened 2023-05-30 20:39 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.2.0 Beta 4

### Miyoo Firmware Version

20230329

### Provide a clear and concise description of the issue

Since upgrading to Beta 4, Onion is not finding all available roms despite the roms being in the correct folder on the SD card. Retroarch is still able to open the roms if launched directly.

### Steps to Reproduce

Upgrade to Onion 4.2.0 Beta 4 and look in the game folders. Several games are missing from my lists despite them still being on the SD card in the appropriate folders.

### Provide any additional context or information that may help us investigate your issue

Many others have reported this issue on Reddit. The main roms affected appear to be Gameboy Color, Gameboy Advance, and SNES, although other lists may also be affected.

**Comment by duckyb** [comment] 2023-05-30 21:48
Which roms are not appearing? I just checked my SD card and I have 110 GBC games while on the MMP I see 88 games in the list. The first game missing from the list is `Blaster Master - Enemy Below (USA, Europe) (SGB Enhanced) (GB Compatible)`.

After refreshing the rom is still missing. However I don't know if it was also missing before the update to beta 3/4.

**Comment by GrouchyM** [comment] 2023-05-30 21:55
> Which roms are not appearing? I just checked my SD card and I have 110 GBC games while on the MMP I see 88 games in the list. The first game missing from the list is `Blaster Master - Enemy Below (USA, Europe) (SGB Enhanced) (GB Compatible)`.
> 
> After refreshing the rom is still missing. However I don't know if it was also missing before the update to beta 3/4.

I’m missing The Legend of Zelda: Link’s Awakening for GBC and all of the Donkey Kong Country games for SNES.

**Comment by duckyb** [comment] 2023-05-30 22:13
@GrouchyM I am also missing that rom on my device. File name is `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible).zip`

**Comment by duckyb** [comment] 2023-05-30 22:15
For the SFC I see `Donkey Kong Country (USA) (Rev 2)` but I am also missing:

- `Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr) (Rev 1)`
- `Donkey Kong Country 3 - Dixie Kong's Double Trouble! (USA) (En,Fr)`

**Comment by GrouchyM** [comment] 2023-05-30 22:19
@duckyb Yes, those titles exactly mirror my missing roms as well.

**Comment by duckyb** [comment] 2023-05-30 22:22
I tried copying DK Country 2 to my PC, extracting the rom and renaming it to `dk2.sfc`. I then copied it back to the Miyoo and refreshed the roms list but the rom still doesn't appear.

**Comment by schmurtzm** [comment] 2023-05-30 23:27
> @GrouchyM I am also missing that rom on my device. File name is `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible).zip`
> 
> For the SFC I see `Donkey Kong Country (USA) (Rev 2)` but I am also missing:
> 
>     * `Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr) (Rev 1)`
> 
>     * `Donkey Kong Country 3 - Dixie Kong's Double Trouble! (USA) (En,Fr)`

Wow indeed  ! And if you remove the `'` then the game is detected by MainUI 😓

**Comment by GrouchyM** [comment] 2023-05-30 23:31
> > @GrouchyM I am also missing that rom on my device. File name is `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible).zip`
> > For the SFC I see `Donkey Kong Country (USA) (Rev 2)` but I am also missing:
> > ```
> > * `Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr) (Rev 1)`
> > 
> > * `Donkey Kong Country 3 - Dixie Kong's Double Trouble! (USA) (En,Fr)`
> > ```
> 
> Wow indeed ! And if you remove the `'` then the game is detected by MainUI 😓

My roms are all formatted according to the No Intro naming convention. They were previously detected.

**Comment by duckyb** [comment] 2023-05-31 00:52
Doesn't seem like the issue is only related to the `'` character, but maybe also to string length? Example:

- [ ] `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible)`
- [ ] `Legend of Zelda, The - Link s Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced)`
- [x] `Legend of Zelda, The - Link s Awakening DX (USA, Europe) (Rev 2)`
- [ ] `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2)`
- [x] `Legend of Zelda, The - Link's Awakening DX (USA, Europe)`
- [ ] `Legend of Zelda, The - Link's Awakening DX '''' (USA, Europe).zip`
- [x] `Legend of Zelda, The - Link's Awakening''''`

![MainUI_001](https://github.com/OnionUI/Onion/assets/27895007/3810fdfe-bc84-4aa6-b8f3-6d2d8d8f7e58)

**Comment by alecvance** [comment] 2023-06-01 03:02
I also noticed this issue and deduced that the missing games in my GBC listing in Onion were in fact those zip files with the longest filenames.

**Comment by OldGameDad** [comment] 2023-06-01 03:22
Final Fantasy IX also won't show up regardless of naming convention.

**Comment by emperordahc** [comment] 2023-06-01 03:35
I also noticed I have a lot of missing ROMs in Onion, all the same ones noted here. They appear using the file explorer tool or can be launched through native RetroArch.

**Comment by schmurtzm** [comment] 2023-06-01 08:05
> Final Fantasy IX also won't show up

Please give the fullname with extension 😉

**Comment by schmurtzm** [comment] 2023-06-01 10:07
Thanks

> Doesn't seem like the issue is only related to the `'` character, but maybe also to string length? Example:
> 
>     * [ ]  `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible)`
> 
>     * [ ]  `Legend of Zelda, The - Link s Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced)`
> 
>     * [x]  `Legend of Zelda, The - Link s Awakening DX (USA, Europe) (Rev 2)`
> 
>     * [ ]  `Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2)`
> 
>     * [x]  `Legend of Zelda, The - Link's Awakening DX (USA, Europe)`
> 
>     * [ ]  `Legend of Zelda, The - Link's Awakening DX '''' (USA, Europe)`
> 
>     * [x]  `Legend of Zelda, The - Link's Awakening''''`
> 
> 
> ![MainUI_001](https://user-images.githubusercontent.com/27895007/242130816-3810fdfe-bc84-4aa6-b8f3-6d2d8d8f7e58.png)

Thanks for the investigation. I have reproduced the problem too with stock on firmware 20230326 so the problem is not really new.  Sadly it's on Miyoo side now... I hope they will solve that quickly.

**Comment by alecvance** [comment] 2023-06-01 14:58
I have the problem in Onion 4.2 Beta 4 but not 4.2 Beta 3. The following file in the /Roms/GBC dir shows up in Beta 3 but not Beta 4:

`Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible)`

It can be seen and played using RetroArch directly.

**Comment by OldGameDad** [comment] 2023-06-01 16:03
> > Final Fantasy IX also won't show up
> 
> Please give the fullname with extension 😉

I did a bunch of work to validate/dig into this. These are my findings:

Final Fantasy 9 cd1.iso - this file had previously shown up in beta 3 but no longer in beta 4 (I know, lousy naming convention)
Also, if I locate this in gamechanger it does indeed work with the same naming and .iso extension.

I procured a new file, that is .bin and .cue extensions, and they seem to SHOW and work as expected, as do all .bin and .cue
Final Fantasy IX (USA) (Disc 1) (Rev 1).bin

This leads me to believe, at least for PSX roms, there is an issue in recognizing .iso files to show within MainUI.

Also to note, the above Donkey Kong, as well as Links Awakening issue, seems to be two-fold in that length as well as commas cause issues in showing in MainUI.

These problems did NOT occur in 4.1.4, so they seem to be new to 4.2 beta 4.

**Comment by schmurtzm** [comment] 2023-06-02 07:46
Well the case of PSX is different and not related to this MainUI bug : 
iso extension is just missing from config.json, I have quickly fixed it here : https://github.com/OnionUI/Onion/commit/072c73c1e676359dce4017e94c8a017a294f1060

.bin files are not showed, only .cue. It's voluntary to avoid roms doublon when we have .cue and .bin in config.json. 
But we have done something to help users on this : in Tweaks app -> Tools -> "Generate CUE files for PSX games"

**Comment by schmurtzm** [comment] 2023-06-02 14:52
Miyoo dev team is on it 🥇 
During this time I've made a script which scan the roms folders and create the SQLite database so we will have a workaround fi the new MainUI takes some time to arrive ;)

**Comment by OldGameDad** [comment] 2023-06-02 17:07
@schmurtzm appreciate you and all your hard work on this! Thank you! are there any temp files or scripts we can run in the meantime?

**Comment by duckyb** [comment] 2023-06-02 17:11
> @schmurtzm appreciate you and all your hard work on this! Thank you! are there any temp files or scripts we can run in the meantime? I did modify the config file for psx, but mainly in reference for rom scanning.

Try to rename your rom to something with less than 50 characters and without symbols like `'`. It might fix the issue while you wait for the official patch.

**Comment by GrouchyM** [comment] 2023-06-02 17:13
> > @schmurtzm appreciate you and all your hard work on this! Thank you! are there any temp files or scripts we can run in the meantime? I did modify the config file for psx, but mainly in reference for rom scanning.
> 
> Try to rename your rom to something with less than 50 characters and without symbols like `'`. It might fix the issue while you wait for the official patch.

This worked for me also.

**Comment by OldGameDad** [comment] 2023-06-02 17:32
> > @schmurtzm appreciate you and all your hard work on this! Thank you! are there any temp files or scripts we can run in the meantime? I did modify the config file for psx, but mainly in reference for rom scanning.
> 
> Try to rename your rom to something with less than 50 characters and without symbols like `'`. It might fix the issue while you wait for the official patch.

This did work, but I wanted to, A. not search for all with less than 50 characters or a  `'`, but I can do that if we don't have a file.

**Comment by schmurtzm** [comment] 2023-06-16 02:49
New beta / Pre-release available with fix included : https://github.com/OnionUI/Onion/releases

**Comment by arongkatz** [comment] 2023-06-16 21:33
> New beta / Pre-release available with fix included : https://github.com/OnionUI/Onion/releases/tag/latest

Just installed this new beta and im still missing the roms. IS there anything i need to do besides installing new update?

**Comment by duckyb** [comment] 2023-06-16 21:44
> im still missing the roms

@arongkatz this is not very helpful. I just checked on my unit and in all game lists I see the same amount of roms as there are zip files in the directory.
If this is not the case for you, you should tell us exactly how many roms are missing and which ones. Or at least give one example.

Make sure you have onion beta version `b321c9a` and the install was successful.

**Comment by arongkatz** [comment] 2023-06-16 23:00
I do have the b321c9a version. Im missing gba and snes roms. Lets say for example i have 155 roms and its only showing 25 until the F titled roms. Its exactly the same way it was showing on the past beta. That is why im asking if there is something else i need to do besides installing yesterdays update. I just reformat the sd card from zero and installed the update and then transfered back the roms.

**Comment by duckyb** [comment] 2023-06-16 23:17
> until the F titled roms

That's odd. I believe your issue is unrelated to this thread. What is the file name of the first missing rom?
All roms begginning with A-E show up?

**Comment by arongkatz** [comment] 2023-06-16 23:25
Here is a screenshot of my gba rom folder [https://imgur.com/a/7dJoo3d](url)

**Comment by duckyb** [comment] 2023-06-16 23:35
Is this a tiny best set collection where you have added two F-ZERO roms? Have you tried deleting `GBA_cache6.db` and rescanning?

**Comment by arongkatz** [comment] 2023-06-16 23:38
Yes this is the tiny best collection. I tried deleting the GBA_cache6.db  on the other beta but let me try on the recent one.

**Comment by arongkatz** [comment] 2023-06-16 23:43
NOPE, Still same issue :(

**Comment by duckyb** [comment] 2023-06-16 23:54
> NOPE, Still same issue :(

Stock SD card? Maybe it's a bad SD
I have almost the same roms, with just a few additions and I'm able to see all of them.

**Comment by arongkatz** [comment] 2023-06-17 00:20
Nop, its a samsung sd card that i was able to use on the first plus compatible beta. It started occuring after i did an ota with the last two week update.

**Comment by duckyb** [comment] 2023-06-17 00:32
I'm afraid I'm out of ideas then

**Comment by schmurtzm** [comment] 2023-06-17 00:37
The requested emulators are enabled in package manager ?

**Comment by arongkatz** [comment] 2023-06-17 00:47
> The requested emulators are enabled in package manager ?

Yes im able to play some games as well but not the ones with G or H and so on

**Comment by dormk23** [comment] 2023-06-17 05:47
Can confirm that this fix works! I had 3 Harry Potter GBA roms with long names (multi language) which was gone before but back now! Thank you so much for the hard work!

**Comment by arongkatz** [comment] 2023-06-19 05:16
So what should I do? I was gonna say try other set or another SD card but I have formatted that SD card several times now and you also have tinys set so...I'm out of ideas

**Comment by duckyb** [comment] 2023-06-19 07:16
> So what should I do? I was gonna say try other set or another SD card but I have formatted that SD card several times now and you also have tinys set so...I'm out of ideas 

Remove all roms and start adding them back a few at a time until it breaks. That way you might learn something new about this bug.

**Comment by arongkatz** [comment] 2023-06-21 01:38
Wanted to update this issue: i re-downloaded the tiny rom set with the new update and packs and now all is working perfectly. I have no idea what may had happened but eveyrthing is back to normal

**Comment by schmurtzm** [comment] 2023-06-21 01:42
The last update from Miyoo include a fix of MainUI binary.
This fix is included in the firmware 202306092122 for Miyoo Mini Plus.
I close this issue.

**Closed by schmurtzm** 2023-06-21 01:42 UTC
Labels: fw/frontend related
