### ISSUE TITLE
All options in "App" fail to load after brief "Loading" screen

### ISSUE THREAD

**Issue by thediamondgeezer** [OnionUI/Onion#934] opened 2023-06-19 11:33 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

96c87c3

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

All options in "App" fail to load after brief "Loading" screen: Tweaks, Search, RetroArch, Package Manager, Onion OTA Update fail to load after brief "Loading" screen then return to App selection menu.

### Steps to Reproduce

Navigate to "App" from the main menu, press "A" to select an entry.

### Provide any additional context or information that may help us investigate your issue

Happens since upgrade new beta

**Comment by dreams897** [comment] 2023-06-19 18:14
Had this problem as well, can't launch Retroarch with latest build

**Comment by Aemiii91** [comment] 2023-06-19 19:18
Duplicate of #912

**Closed by Aemiii91** 2023-06-19 19:18 UTC
