### ISSUE TITLE
Missing roms in GBA and GB after Onion V4.2.0-beta-dev Pre-release in Miyoo Mini plus

### ISSUE THREAD

**Issue by arongkatz** [OnionUI/Onion#885] opened 2023-06-06 02:06 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS (Note that Onion devs can’t fix inherited issues with RA Cores)
- [X] I have reviewed the [Onion Wiki](https://github.com/OnionUI/Onion/wiki) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

Onion V4.2.0-beta-dev Pre-release

### Miyoo Firmware Version

202303262339

### Provide a clear and concise description of the issue

Im missing more than half the roms i currently have on my folders on GBA and GB collections. Already tried refreshing roms and going back to previous beta and im getting the same result

### Steps to Reproduce

Select - refresh roms

### Provide any additional context or information that may help us investigate your issue

Using Miyoo Mini Plus

**Comment by Aemiii91** [comment] 2023-06-06 04:45
Duplicate of #852

**Closed by Aemiii91** 2023-06-06 04:45 UTC
