### ISSUE TITLE
Activity Tracker has Missing Thumbs

### ISSUE THREAD

**Issue by Prozi** [OnionUI/Onion#1441] opened 2024-02-25 20:42 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

4.3.0-RC-b66469de

### Miyoo Firmware Version

202306282128

### Provide a clear and concise description of the issue

more than 14 days ago I've opened an issue https://github.com/OnionUI/Onion/issues/1419 that was later closed, then it was supposed to be followed up but was disregarded.

I have asked for issue to be reopened as it is a bug, and it exists, and is not fixed, but I was ignored.

I am attaching a video of the issue so I hope this time you won't say it doesn't exist or something.

### Steps to Reproduce

please see video to know how to reproduce,
the thumbs are visible in Favorites but not in Activity Tracker

https://github.com/OnionUI/Onion/assets/3052357/4ebe536c-aa32-4fcb-8f52-5d324136828a

### Provide any additional context or information that may help us investigate your issue

-

**Comment by Aemiii91** [comment] 2024-02-25 20:47
Duplicate of #1221

**Closed by Aemiii91** 2024-02-25 20:47 UTC
