### ISSUE TITLE
v4.3.1-1 doesn't work with miyoo mini V4 Firmware 202408061133

### ISSUE THREAD

**Issue by CyberWW** [OnionUI/Onion#1720] opened 2024-12-21 11:22 UTC
### Checklist

- [X] I am reporting a bug in the Onion OS - Any issues with the closed source frontend ([MainUI](https://github.com/OnionUI/MainUI-issues)), or [RetroArch](https://github.com/libretro/RetroArch) or any of the cores should be directed to their respective repositories
- [X] I have reviewed the [Onion Docs](https://onionui.github.io/docs) and did not find the answer
- [X] I have searched the existing (open and closed) issues to ensure I do not log a duplicate

### Onions OS Version

V4.3.1

### Miyoo Firmware Version

202408061133

### Provide a clear and concise description of the issue

just get the new bath miyoo mini v4 come with the SD card
the RetroArch doesn't identify the screen as 560P
and the system UI still working under 480P

### Steps to Reproduce

update the Firmware to 202408061133 and clean install the v4.3.1-1

### Provide any additional context or information that may help us investigate your issue

[miyoo283_fw.zip](https://github.com/user-attachments/files/18218313/miyoo283_fw.zip)

**Comment by Aemiii91** [comment] 2024-12-21 11:24
Duplicate of #1709

**Closed by Aemiii91** 2024-12-21 11:24 UTC
